version: '3.7'

services:
  kurisu:
    image: kurisu:latest
    volumes:
       # The SQLite database is saved here, so use a docker volume for persistent data
     - kurisu-data:/app/src/data
       # The config needs to be in the same location as this file
     - ./config.toml:/app/src/data/config.toml:ro

volumes:
  kurisu-data: {}