eightball = [
    "As I see it, yes.",
    "Ask again later.",
    "Better not tell you now.",
    "Cannot predict now.",
    "Concentrate and ask again.",
    "Don\’t count on it.",
    "It is certain.",
    "It is decidedly so.",
    "Most likely.",
    "My reply is no.",
    "My sources say no.",
    "Outlook not so good.",
    "Outlook good.",
    "Reply hazy, try again.",
    "Signs point to yes.",
    "Very doubtful.",
    "Without a doubt.",
    "Yes.",
    "No",
    "Yes – definitely.",
    "You may rely on it.",
]

compliments = [
    "Your positivity is infectious.",
    "You should be so proud of yourself.",
    "You\’re amazing!",
    "You\’re a true gift to the people in your life.",
    "You\’re an incredible friend.",
    "I really appreciate everything that you do.",
    "You inspire me to be a better person.",
    "Your passion always motivates me.",
    "Your smile makes me smile.",
    "Thank you for being such a great person.",
    "The way you carry yourself is truly admirable.",
    "You are such a good listener.",
    "You have a remarkable sense of humor.",
    "Thanks for being you!",
    "You set a great example for everyone around you.",
    "I love your perspective on life.",
    "Being around you makes everything better.",
    "You always know the right thing to say.",
    "The world would be a better place if more people were like you!",
    "You are one of a kind.",
    "You make me want to be the best version of myself.",
    "You always have the best ideas.",
    "I\’m so lucky to have you in my life.",
    "Your capacity for generosity knows no bounds.",
    "I wish I were more like you.",
    "You are so strong.",
    "I\’ve never met someone as kind as you are.",
    "You have such a great heart.",
    "Simply knowing you has made me a better person.",
    "You are beautiful inside and out.",
]
